In [10]:
import csv
with open("/Users/mani/sample.csv",'r') as csv_file:
    csv_reader = csv.reader(csv_file)
    for line in csv_reader:
        print(line)

['first_name', 'last_name', 'mail']
['mani', 'k', 'abc@gmail.com']
['ravi', 'g', 'cde@gmail.com']

In [1]:
import csv
with open("/Users/mani/sample.csv",'r') as csv_file:
    csv_reader = csv.reader(csv_file)
    with open("/Users/mani/samplewrite.csv",'w') as csv_file:
        csv_writer = csv.writer(csv_file)
        for line in csv_reader:
            csv_writer.writerow(line)

In [2]:
import csv
with open("/Users/mani/samplewritedict.csv",'r') as csv_file:
    csv_reader = csv.reader(csv_file)
    for line in csv_reader:
        print(line)

['first_name', 'last_name']
['mani', 'k']
['ravi', 'g']

In [3]:
import csv
with open("/Users/mani/sample.csv",'r') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    with open("/Users/mani/samplewritedict.csv",'w') as csv_file:
        fieldnames = ['first_name', 'last_name']
        csv_writer = csv.DictWriter(csv_file,fieldnames=fieldnames)
        csv_writer.writeheader()
        for line in csv_reader:
            del line['mail']
            csv_writer.writerow(line)

In [4]:
import csv
def read_csv(file_path):   
    data=[]
    with open(file_path,'r') as od:
        csv_reader = csv.DictReader(od)
        for line in csv_reader:
            data.append(line)
    return data

data = read_csv("/Users/mani/orders.csv")
print(data)

[{'id': '1', 'customer': 'A', 'amount': '100'}, {'id': '2', 'customer': 'B', 'amount': '200'}, {'id': '3', 'customer': 'C', 'amount': 'invalid'}, {'id': '4', 'customer': 'A', 'amount': '300'}, {'id': '5', 'customer': 'B', 'amount': '50'}]

In [5]:
import pandas as pd
df=pd.read_csv("pokemon_data.csv")
print(df.head(3))

   #       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0  1  Bulbasaur  Grass  Poison  45      49       49       65       65     45
1  2    Ivysaur  Grass  Poison  60      62       63       80       80     60
2  3   Venusaur  Grass  Poison  80      82       83      100      100     80

   Generation  Legendary
0           1      False
1           1      False
2           1      False

In [6]:
print(df[['Name','Type 1','HP']])

                      Name   Type 1  HP
0                Bulbasaur    Grass  45
1                  Ivysaur    Grass  60
2                 Venusaur    Grass  80
3    VenusaurMega Venusaur    Grass  80
4               Charmander     Fire  39
..                     ...      ...  ..
795                Diancie     Rock  50
796    DiancieMega Diancie     Rock  50
797    HoopaHoopa Confined  Psychic  80
798     HoopaHoopa Unbound  Psychic  80
799              Volcanion     Fire  80

[800 rows x 3 columns]

In [7]:
df.loc[df['Type 1']=='Grass']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False

In [8]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [9]:
df.sort_values('Name')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [15]:
df['Total']=df['HP']+df['Attack']+df['Defense']+df['Sp. Atk']+df['Sp. Def']+df['Speed']

df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [14]:
df=df.drop(columns='Total')
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [16]:
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [19]:
cols = list(df.columns)
df = df[cols[0:4]+[cols[-1]]+cols[4:12]]

In [20]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [23]:
df.to_csv('modified.csv',index=False)

In [ ]:
df.loc[df['Type 1']=='Grass']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,313,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,405,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,530,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False

In [29]:
import re
df.loc[df['Type 1'].str.contains('fire|grass',flags=re.I,regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [35]:
df=pd.read_csv('modified.csv')
df.groupby(['Type 1']).sum()

,#,Name,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,,
Bug,23080,CaterpieMetapodButterfreeWeedleKakunaBeedrillB...,FlyingPoisonPoisonPoisonPoisonGrassGrassPoison...,26146,3925,4897,4880,3717,4471,4256,222,0
Dark,14302,UmbreonMurkrowSneaselHoundourHoundoomHoundoomM...,FlyingIceFireFireFireGhostGhostFlyingIceFighti...,13818,2071,2740,2177,2314,2155,2361,125,2
Dragon,15180,DratiniDragonairDragoniteAltariaAltariaMega Al...,FlyingFlyingFairyFlyingFlyingPsychicPsychicPsy...,17617,2666,3588,2764,3099,2843,2657,124,12
Electric,15994,PikachuRaichuMagnemiteMagnetonVoltorbElectrode...,SteelSteelFlyingDragonSteelGhostFireWaterIceFl...,19510,2631,3040,2917,3961,3243,3718,144,4
Fairy,7642,ClefairyClefableCleffaTogepiTogeticSnubbullGra...,FlyingFlying,7024,1260,1046,1117,1335,1440,826,70,1
Fighting,9824,MankeyPrimeapeMachopMachokeMachampHitmonleeHit...,PsychicPsychicPsychicSteelSteelDarkFlying,11244,1886,2613,1780,1434,1747,1784,91,0
Fire,17025,CharmanderCharmeleonCharizardCharizardMega Cha...,FlyingDragonFlyingFlyingRockFlyingFightingFigh...,23820,3635,4408,3524,4627,3755,3871,167,5
Flying,2711,TornadusIncarnate FormeTornadusTherian FormeNo...,DragonDragon,1940,283,315,265,377,290,410,22,2
Ghost,15568,GastlyHaunterGengarGengarMega GengarMisdreavus...,PoisonPoisonPoisonPoisonFlyingFlyingDarkDragon...,14066,2062,2361,2598,2539,2447,2059,134,2
Grass,24141,BulbasaurIvysaurVenusaurVenusaurMega VenusaurO...,PoisonPoisonPoisonPoisonPoisonPoisonPoisonPois...,29480,4709,5125,4956,5425,4930,4335,235,3
Ground,11401,SandshrewSandslashDiglettDugtrioCuboneMarowakR...,RockRockFlyingDragonDragonPsychicPsychicFireRo...,14000,2361,3064,2715,1807,2008,2045,101,4
Ice,10165,JynxArticunoSwinubPiloswineDelibirdSmoochumSno...,PsychicFlyingGroundGroundFlyingPsychicWaterWat...,10403,1728,1746,1714,1861,1831,1523,85,2
Normal,31279,PidgeyPidgeottoPidgeotPidgeotMega PidgeotRatta...,FlyingFlyingFlyingFlyingFlyingFlyingFairyFairy...,39365,7573,7200,5865,5470,6245,7012,299,2
Poison,7050,EkansArbokNidoran (Female)NidorinaNidoqueenNid...,GroundGroundFlyingFlyingFlyingDarkDarkBugDarkF...,11176,1883,2091,1927,1692,1803,1780,71,0
Psychic,21706,AbraKadabraAlakazamAlakazamMega AlakazamDrowze...,FairyFightingFlyingFlyingFlyingGrassFairyFairy...,27129,4026,4073,3858,5609,4918,4645,193,14
Rock,17280,GeodudeGravelerGolemOnixOmanyteOmastarKabutoKa...,GroundGroundGroundGroundWaterWaterWaterWaterFl...,19965,2876,4086,4435,2787,3321,2460,152,4
Steel,11957,SteelixSteelixMega SteelixSkarmoryMawileMawile...,GroundGroundFlyingFairyFairyRockRockRockPsychi...,13168,1761,2503,3412,1823,2177,1492,104,4
Water,33946,SquirtleWartortleBlastoiseBlastoiseMega Blasto...,FightingPoisonPoisonPsychicPsychicPsychicIceIc...,48211,8071,8305,8170,8379,7898,7388,320,4

In [37]:
df=pd.read_csv("/Users/mani/orders.csv")

In [39]:
df["amount"] = pd.to_numeric(df["amount"],errors="coerce")
df=df.dropna()

In [41]:
total_revenue = df["amount"].sum()

In [42]:
print(total_revenue)

650.0

In [43]:
grouped_data = df.groupby('customer')["amount"].sum()
print(grouped_data)

customer
A    400.0
B    250.0
Name: amount, dtype: float64

In [ ]:
Load CSV
clean invalid values
calculate total_revenue revenue per cusotmer
save output customer_summary.txt

Total revnue: 650
Revenue by Customer:
A:400
B: 250

def load_data(file_path)
    pass
def clean_data(df)
    pass
def calculate_metrics(df)
    pass
def save_sumary(file_path,total,grouped)
    pass

SyntaxError: invalid syntax (2516451011.py, line 1)

In [103]:
def load_data(file_path):
    df=pd.read_csv("/Users/mani/orders.csv")
    return df
def clean_data(df):
    df["amount"] = pd.to_numeric(df["amount"],errors="coerce")
    df=df.dropna()
    return df
def calculate_metrics(df):
    total = df["amount"].sum()
    grouped = df.groupby('customer')["amount"].sum()
    return total,grouped
def save_summary(file_path,total,grouped):
    with open(file_path,"w") as f:
        f.write(f"Total Revenue:{total}\n")
        f.write(f"Revenue per Customer:\n")
        for customer, revenue in grouped.items():
            f.write(f"{customer}: {revenue}\n")
    
file_path="/Users/mani/orders.csv"
df=load_data(file_path)
df=clean_data(df)
calculate_metrics(df)
total,grouped=calculate_metrics(df)
save_summary("customer_summary.txt",total,grouped)

In [77]:
df=pd.read_csv("/Users/mani/orders.csv")
df

   id customer   amount
0   1        A      100
1   2        B      200
2   3        C  invalid
3   4        A      300
4   5        B       50